/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InternRouteImport } from './routes/intern'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternIndexRouteImport } from './routes/intern.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InternUpdatesRouteImport } from './routes/intern.updates'
import { Route as InternTasksRouteImport } from './routes/intern.tasks'
import { Route as InternRequestsRouteImport } from './routes/intern.requests'
import { Route as InternPerformanceRouteImport } from './routes/intern.performance'
import { Route as InternChatRouteImport } from './routes/intern.chat'
import { Route as InternCalendarRouteImport } from './routes/intern.calendar'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminInternsRouteImport } from './routes/admin.interns'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InternRoute = InternRouteImport.update({
  id: '/intern',
  path: '/intern',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternIndexRoute = InternIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InternRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InternUpdatesRoute = InternUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => InternRoute,
} as any)
const InternTasksRoute = InternTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => InternRoute,
} as any)
const InternRequestsRoute = InternRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => InternRoute,
} as any)
const InternPerformanceRoute = InternPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => InternRoute,
} as any)
const InternChatRoute = InternChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => InternRoute,
} as any)
const InternCalendarRoute = InternCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => InternRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInternsRoute = AdminInternsRouteImport.update({
  id: '/interns',
  path: '/interns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/intern': typeof InternRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/interns': typeof AdminInternsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/intern/calendar': typeof InternCalendarRoute
  '/intern/chat': typeof InternChatRoute
  '/intern/performance': typeof InternPerformanceRoute
  '/intern/requests': typeof InternRequestsRoute
  '/intern/tasks': typeof InternTasksRoute
  '/intern/updates': typeof InternUpdatesRoute
  '/admin/': typeof AdminIndexRoute
  '/intern/': typeof InternIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/interns': typeof AdminInternsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/intern/calendar': typeof InternCalendarRoute
  '/intern/chat': typeof InternChatRoute
  '/intern/performance': typeof InternPerformanceRoute
  '/intern/requests': typeof InternRequestsRoute
  '/intern/tasks': typeof InternTasksRoute
  '/intern/updates': typeof InternUpdatesRoute
  '/admin': typeof AdminIndexRoute
  '/intern': typeof InternIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/intern': typeof InternRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/interns': typeof AdminInternsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/intern/calendar': typeof InternCalendarRoute
  '/intern/chat': typeof InternChatRoute
  '/intern/performance': typeof InternPerformanceRoute
  '/intern/requests': typeof InternRequestsRoute
  '/intern/tasks': typeof InternTasksRoute
  '/intern/updates': typeof InternUpdatesRoute
  '/admin/': typeof AdminIndexRoute
  '/intern/': typeof InternIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/intern'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/interns'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/tasks'
    | '/intern/calendar'
    | '/intern/chat'
    | '/intern/performance'
    | '/intern/requests'
    | '/intern/tasks'
    | '/intern/updates'
    | '/admin/'
    | '/intern/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/interns'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/tasks'
    | '/intern/calendar'
    | '/intern/chat'
    | '/intern/performance'
    | '/intern/requests'
    | '/intern/tasks'
    | '/intern/updates'
    | '/admin'
    | '/intern'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/intern'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/interns'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/tasks'
    | '/intern/calendar'
    | '/intern/chat'
    | '/intern/performance'
    | '/intern/requests'
    | '/intern/tasks'
    | '/intern/updates'
    | '/admin/'
    | '/intern/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InternRoute: typeof InternRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern': {
      id: '/intern'
      path: '/intern'
      fullPath: '/intern'
      preLoaderRoute: typeof InternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/': {
      id: '/intern/'
      path: '/'
      fullPath: '/intern/'
      preLoaderRoute: typeof InternIndexRouteImport
      parentRoute: typeof InternRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/intern/updates': {
      id: '/intern/updates'
      path: '/updates'
      fullPath: '/intern/updates'
      preLoaderRoute: typeof InternUpdatesRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/tasks': {
      id: '/intern/tasks'
      path: '/tasks'
      fullPath: '/intern/tasks'
      preLoaderRoute: typeof InternTasksRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/requests': {
      id: '/intern/requests'
      path: '/requests'
      fullPath: '/intern/requests'
      preLoaderRoute: typeof InternRequestsRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/performance': {
      id: '/intern/performance'
      path: '/performance'
      fullPath: '/intern/performance'
      preLoaderRoute: typeof InternPerformanceRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/chat': {
      id: '/intern/chat'
      path: '/chat'
      fullPath: '/intern/chat'
      preLoaderRoute: typeof InternChatRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/calendar': {
      id: '/intern/calendar'
      path: '/calendar'
      fullPath: '/intern/calendar'
      preLoaderRoute: typeof InternCalendarRouteImport
      parentRoute: typeof InternRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interns': {
      id: '/admin/interns'
      path: '/interns'
      fullPath: '/admin/interns'
      preLoaderRoute: typeof AdminInternsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminInternsRoute: typeof AdminInternsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminInternsRoute: AdminInternsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InternRouteChildren {
  InternCalendarRoute: typeof InternCalendarRoute
  InternChatRoute: typeof InternChatRoute
  InternPerformanceRoute: typeof InternPerformanceRoute
  InternRequestsRoute: typeof InternRequestsRoute
  InternTasksRoute: typeof InternTasksRoute
  InternUpdatesRoute: typeof InternUpdatesRoute
  InternIndexRoute: typeof InternIndexRoute
}

const InternRouteChildren: InternRouteChildren = {
  InternCalendarRoute: InternCalendarRoute,
  InternChatRoute: InternChatRoute,
  InternPerformanceRoute: InternPerformanceRoute,
  InternRequestsRoute: InternRequestsRoute,
  InternTasksRoute: InternTasksRoute,
  InternUpdatesRoute: InternUpdatesRoute,
  InternIndexRoute: InternIndexRoute,
}

const InternRouteWithChildren =
  InternRoute._addFileChildren(InternRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InternRoute: InternRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
